# Generated by Django 3.1.5 on 2021-01-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(default='no title', max_length=25),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='title',
            field=models.CharField(default='submenu with no title', max_length=25),
        ),
    ]
